name=HP5883
version=1.0.0
author=Radion
maintainer=Radion
sentence=Library for HP5883 / QMC5883P magnetometer.
paragraph=Fast lightweight driver for HP5883 (QMC5883P) without dependencies.
category=Sensors
url=https://github.com/ТВОЙ_GITHUB/HP5883
architectures=*
